# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160228_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='time_edited',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
